sudo: required
services:
  - docker

before_install:
  - docker build -t eonsubae/docker-aws-react-test -f Dockerfile.dev .

script:
  - docker container run eonsubae/docker-aws-react-test npm run test -- --coverage
